#!/usr/bin/env python3
# scripts/summarize_powergrid_lgode.py

"""
Aggregate power-grid LG-ODE experiment result JSON files.

Outputs
-------
results.csv
    One standardized row per experiment result JSON, including normalized,
    physical-unit, physics-consistency, runtime, and parameter-count metrics.

summary.csv
    Aggregated by:
        task
        observed_fraction
        model

    Reports:
        normalized MSE and MAE
        voltage-magnitude MAE in p.u.
        voltage-angle MAE in degrees
        active-power MAE in MW
        reactive-power MAE in MVAr
        active and reactive AC residuals
        voltage-violation rate
        validation statistics
        runtime
        parameter counts

paired_comparisons.csv
    Seed-paired comparisons:

        AT-ODE versus LG-ODE
        LG-ODE versus Latent ODE
        AT-ODE versus Latent ODE

    The relative MSE improvement for model A versus model B is:

        100 * (MSE_B - MSE_A) / MSE_B

    Therefore, the main AT-ODE transport improvement is:

        100 * (MSE_LGODE - MSE_ATODE) / MSE_LGODE

Notes
-----
Normalized MSE remains the primary checkpoint-selection and paired-comparison
metric. Physical-unit feature metrics and AC-consistency metrics are retained
as separate reporting metrics; they are not silently folded into the training
objective.

Physical metrics are written to the CSV outputs even if older result files do
not contain them. Missing values are represented as NaN. Use
``--require-physical-metrics`` to reject result files that do not contain all
required physical reporting metrics.

Example
-------
python scripts/summarize_powergrid_lgode.py \\
    --input-dir results/powergrid_lgode \\
    --output-dir results/powergrid_lgode/summary \\
    --require-physical-metrics
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
import tempfile
import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple

import numpy as np
import pandas as pd


MODEL_ORDER = [
    "persistence",
    "latentode",
    "lgode",
    "atode",
]

TASK_ORDER = [
    "interpolation",
    "extrapolation",
]

OBSERVATION_FRACTION_ORDER = [
    0.4,
    0.6,
    0.8,
]

PAIRED_COMPARISONS = [
    ("atode", "lgode", "AT-ODE versus LG-ODE"),
    ("lgode", "latentode", "LG-ODE versus Latent ODE"),
    ("atode", "latentode", "AT-ODE versus Latent ODE"),
]

PHYSICAL_METRIC_COLUMNS = [
    "voltage_magnitude_mae_pu",
    "voltage_angle_mae_deg",
    "active_power_mae_mw",
    "reactive_power_mae_mvar",
    "ac_active_power_residual_mae_mw",
    "ac_reactive_power_residual_mae_mvar",
    "voltage_violation_rate",
]


@dataclass(frozen=True)
class ParsedResult:
    """One standardized experiment result."""

    source_file: str
    simbench_code: str
    task: str
    observed_fraction: float
    model: str
    seed: int
    mask_seed: int

    # Normalized-space metrics.
    normalized_test_mse: float
    normalized_test_mae: float
    normalized_test_mse_full: float
    normalized_test_mae_full: float
    normalized_test_mse_unobserved: float
    normalized_test_mae_unobserved: float

    # Physical-unit feature metrics.
    voltage_magnitude_mae_pu: float
    voltage_angle_mae_deg: float
    active_power_mae_mw: float
    reactive_power_mae_mvar: float

    # Physics-consistency metrics.
    ac_active_power_residual_mae_mw: float
    ac_reactive_power_residual_mae_mvar: float
    voltage_violation_rate: float

    # Validation/training information.
    best_validation_epoch: int
    best_validation_mse: float
    training_time_seconds: float
    parameter_count: int
    trainable_parameter_count: int

    # Window/data configuration.
    trajectory_length: Optional[int]
    context_length: Optional[int]
    forecast_length: Optional[int]
    stride: Optional[int]
    batch_size: Optional[int]

    # Optional prediction artifact generated by the runner.
    prediction_path: str
    alias: str

    def as_dict(self) -> Dict[str, Any]:
        return {
            "source_file": self.source_file,
            "simbench_code": self.simbench_code,
            "task": self.task,
            "observed_fraction": self.observed_fraction,
            "model": self.model,
            "seed": self.seed,
            "mask_seed": self.mask_seed,
            "normalized_test_mse": self.normalized_test_mse,
            "normalized_test_mae": self.normalized_test_mae,
            "normalized_test_mse_full": self.normalized_test_mse_full,
            "normalized_test_mae_full": self.normalized_test_mae_full,
            "normalized_test_mse_unobserved": (
                self.normalized_test_mse_unobserved
            ),
            "normalized_test_mae_unobserved": (
                self.normalized_test_mae_unobserved
            ),
            "voltage_magnitude_mae_pu": (
                self.voltage_magnitude_mae_pu
            ),
            "voltage_angle_mae_deg": self.voltage_angle_mae_deg,
            "active_power_mae_mw": self.active_power_mae_mw,
            "reactive_power_mae_mvar": self.reactive_power_mae_mvar,
            "ac_active_power_residual_mae_mw": (
                self.ac_active_power_residual_mae_mw
            ),
            "ac_reactive_power_residual_mae_mvar": (
                self.ac_reactive_power_residual_mae_mvar
            ),
            "voltage_violation_rate": self.voltage_violation_rate,
            "best_validation_epoch": self.best_validation_epoch,
            "best_validation_mse": self.best_validation_mse,
            "training_time_seconds": self.training_time_seconds,
            "parameter_count": self.parameter_count,
            "trainable_parameter_count": (
                self.trainable_parameter_count
            ),
            "trajectory_length": self.trajectory_length,
            "context_length": self.context_length,
            "forecast_length": self.forecast_length,
            "stride": self.stride,
            "batch_size": self.batch_size,
            "prediction_path": self.prediction_path,
            "alias": self.alias,
        }


def _normalize_key(key: str) -> str:
    return (
        str(key)
        .strip()
        .lower()
        .replace("-", "_")
        .replace(" ", "_")
    )


def _flatten_mapping(
    value: Mapping[str, Any],
    prefix: str = "",
) -> Dict[str, Any]:
    """
    Flatten a nested JSON mapping using normalized dotted keys.

    Example
    -------
    {"test": {"physical_metrics": {"voltage_magnitude_mae_pu": 0.01}}}

    becomes:

    {"test.physical_metrics.voltage_magnitude_mae_pu": 0.01}
    """

    flattened: Dict[str, Any] = {}

    for raw_key, item in value.items():
        key = _normalize_key(raw_key)
        full_key = f"{prefix}.{key}" if prefix else key

        if isinstance(item, Mapping):
            flattened.update(
                _flatten_mapping(item, prefix=full_key)
            )
        else:
            flattened[full_key] = item

    return flattened


def _candidate_value(
    flattened: Mapping[str, Any],
    candidates: Sequence[str],
    *,
    default: Any = None,
    required: bool = False,
    field_name: Optional[str] = None,
) -> Any:
    """Return the first non-null value matching a candidate key."""

    normalized_candidates = [
        ".".join(
            _normalize_key(part)
            for part in candidate.split(".")
        )
        for candidate in candidates
    ]

    for candidate in normalized_candidates:
        if (
            candidate in flattened
            and flattened[candidate] is not None
        ):
            return flattened[candidate]

    # Support result wrappers such as
    # "results.test.physical_metrics.voltage_magnitude_mae_pu".
    for candidate in normalized_candidates:
        suffix = f".{candidate}"
        matches = [
            value
            for key, value in flattened.items()
            if key.endswith(suffix) and value is not None
        ]

        if len(matches) == 1:
            return matches[0]

    if required:
        label = field_name or "/".join(candidates)
        raise KeyError(f"Missing required result field: {label}")

    return default


def _to_float(
    value: Any,
    field_name: str,
    *,
    finite: bool = True,
) -> float:
    if isinstance(value, bool):
        raise ValueError(
            f"{field_name} must be numeric, not boolean"
        )

    try:
        result = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(
            f"{field_name} must be numeric; got {value!r}"
        ) from exc

    if finite and not math.isfinite(result):
        raise ValueError(
            f"{field_name} must be finite; got {result}"
        )

    return result


def _optional_float(
    flattened: Mapping[str, Any],
    candidates: Sequence[str],
    field_name: str,
    *,
    required: bool,
) -> float:
    value = _candidate_value(
        flattened,
        candidates,
        default=None,
        required=required,
        field_name=field_name,
    )

    if value is None:
        return float("nan")

    return _to_float(value, field_name)


def _to_int(value: Any, field_name: str) -> int:
    if isinstance(value, bool):
        raise ValueError(
            f"{field_name} must be an integer, not boolean"
        )

    try:
        numeric = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(
            f"{field_name} must be an integer; got {value!r}"
        ) from exc

    if not math.isfinite(numeric) or not numeric.is_integer():
        raise ValueError(
            f"{field_name} must be an integer; got {value!r}"
        )

    return int(numeric)


def _optional_int(
    value: Any,
    field_name: str,
) -> Optional[int]:
    if value is None:
        return None

    return _to_int(value, field_name)


def _normalize_model_name(value: Any) -> str:
    model = _normalize_key(str(value))

    aliases = {
        "copy_persistence": "persistence",
        "copypersistence": "persistence",
        "persistencebaseline": "persistence",
        "persistence_baseline": "persistence",
        "latent_ode": "latentode",
        "independent_latent_ode": "latentode",
        "independentlatentode": "latentode",
        "lg_ode": "lgode",
        "at_ode": "atode",
        "attention_transport_ode": "atode",
        "attentiontransportode": "atode",
    }

    model = aliases.get(model, model)

    if model not in MODEL_ORDER:
        raise ValueError(
            f"Unknown model {value!r}; expected one of {MODEL_ORDER}"
        )

    return model


def _display_model_name(model: str) -> str:
    names = {
        "persistence": "Persistence",
        "latentode": "Latent ODE",
        "lgode": "LG-ODE",
        "atode": "AT-ODE",
    }
    return names.get(model, model)


def _normalize_task_name(value: Any) -> str:
    task = _normalize_key(str(value))

    aliases = {
        "interp": "interpolation",
        "interpolate": "interpolation",
        "extrap": "extrapolation",
        "forecast": "extrapolation",
        "forecasting": "extrapolation",
    }

    task = aliases.get(task, task)

    if task not in TASK_ORDER:
        raise ValueError(
            f"Unknown task {value!r}; expected one of {TASK_ORDER}"
        )

    return task


def _normalize_observed_fraction(value: Any) -> float:
    fraction = _to_float(value, "observed_fraction")

    if fraction in {40.0, 60.0, 80.0}:
        fraction /= 100.0

    for allowed in OBSERVATION_FRACTION_ORDER:
        if math.isclose(
            fraction,
            allowed,
            rel_tol=0.0,
            abs_tol=1e-9,
        ):
            return allowed

    raise ValueError(
        "observed_fraction must be 0.4, 0.6 or 0.8; "
        f"got {fraction}"
    )


def _validate_nonnegative_metric(
    value: float,
    name: str,
    path: Path,
) -> None:
    if math.isfinite(value) and value < 0.0:
        raise ValueError(
            f"{name} cannot be negative in {path}; got {value}"
        )


def _validate_rate(
    value: float,
    name: str,
    path: Path,
) -> None:
    if not math.isfinite(value):
        return

    if value < 0.0 or value > 1.0:
        raise ValueError(
            f"{name} must lie within [0, 1] in {path}; got {value}"
        )


def _parse_result_json(
    path: Path,
    input_directory: Path,
    *,
    require_physical_metrics: bool,
) -> ParsedResult:
    try:
        with path.open("r", encoding="utf-8") as handle:
            raw = json.load(handle)
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(
            f"Could not read JSON file {path}"
        ) from exc

    if not isinstance(raw, Mapping):
        raise ValueError(
            f"Result JSON must contain an object: {path}"
        )

    flattened = _flatten_mapping(raw)

    model = _normalize_model_name(
        _candidate_value(
            flattened,
            [
                "model",
                "model_name",
                "config.model",
                "config.model_name",
                "args.model",
                "arguments.model",
                "experiment.model",
            ],
            required=True,
            field_name="model",
        )
    )

    task = _normalize_task_name(
        _candidate_value(
            flattened,
            [
                "task",
                "config.task",
                "args.task",
                "arguments.task",
                "experiment.task",
            ],
            required=True,
            field_name="task",
        )
    )

    observed_fraction = _normalize_observed_fraction(
        _candidate_value(
            flattened,
            [
                "observed_fraction",
                "observation_fraction",
                "sample_percent",
                "config.observed_fraction",
                "config.observation_fraction",
                "args.observed_fraction",
                "arguments.observed_fraction",
                "experiment.observed_fraction",
            ],
            required=True,
            field_name="observed_fraction",
        )
    )

    seed = _to_int(
        _candidate_value(
            flattened,
            [
                "seed",
                "random_seed",
                "config.seed",
                "config.random_seed",
                "args.seed",
                "args.random_seed",
                "arguments.seed",
                "experiment.seed",
            ],
            required=True,
            field_name="seed",
        ),
        "seed",
    )

    mask_seed = _to_int(
        _candidate_value(
            flattened,
            [
                "mask_seed",
                "config.mask_seed",
                "args.mask_seed",
                "arguments.mask_seed",
                "experiment.mask_seed",
            ],
            default=seed,
        ),
        "mask_seed",
    )

    normalized_test_mse = _to_float(
        _candidate_value(
            flattened,
            [
                "test.normalized_mse",
                "test.normalized_test_mse",
                "test.metrics.normalized_mse",
                "test.metrics.mse",
                "metrics.test.normalized_mse",
                "metrics.test.mse",
                "normalized_test_mse",
                "test_mse",
                "test_mse_normalized",
                "results.test.normalized_mse",
                "results.test.mse",
            ],
            required=True,
            field_name="normalized test MSE",
        ),
        "normalized_test_mse",
    )

    normalized_test_mae = _to_float(
        _candidate_value(
            flattened,
            [
                "test.normalized_mae",
                "test.normalized_test_mae",
                "test.metrics.normalized_mae",
                "test.metrics.mae",
                "metrics.test.normalized_mae",
                "metrics.test.mae",
                "normalized_test_mae",
                "test_mae",
                "test_mae_normalized",
                "results.test.normalized_mae",
                "results.test.mae",
            ],
            required=True,
            field_name="normalized test MAE",
        ),
        "normalized_test_mae",
    )

    normalized_test_mse_full = _to_float(
        _candidate_value(
            flattened,
            ["test.normalized_mse_full"],
            default=normalized_test_mse,
        ),
        "normalized_test_mse_full",
    )
    normalized_test_mae_full = _to_float(
        _candidate_value(
            flattened,
            ["test.normalized_mae_full"],
            default=normalized_test_mae,
        ),
        "normalized_test_mae_full",
    )
    normalized_test_mse_unobserved = _optional_float(
        flattened,
        ["test.normalized_mse_unobserved"],
        "normalized_test_mse_unobserved",
        required=False,
    )
    normalized_test_mae_unobserved = _optional_float(
        flattened,
        ["test.normalized_mae_unobserved"],
        "normalized_test_mae_unobserved",
        required=False,
    )

    # ------------------------------------------------------------------
    # Physical-unit feature metrics
    # ------------------------------------------------------------------

    voltage_magnitude_mae_pu = _optional_float(
        flattened,
        [
            "voltage_magnitude_mae_pu",
            "test.voltage_magnitude_mae_pu",
            "test.physical.voltage_magnitude_mae_pu",
            "test.physical_metrics.voltage_magnitude_mae_pu",
            "test.metrics.voltage_magnitude_mae_pu",
            "metrics.test.voltage_magnitude_mae_pu",
            "physical_metrics.voltage_magnitude_mae_pu",
            "physical.voltage_magnitude_mae_pu",
            "test.vm_mae_pu",
            "test.v_mag_mae_pu",
            "vm_mae_pu",
            "v_mag_mae_pu",
        ],
        "voltage_magnitude_mae_pu",
        required=require_physical_metrics,
    )

    voltage_angle_mae_deg = _optional_float(
        flattened,
        [
            "voltage_angle_mae_deg",
            "test.voltage_angle_mae_deg",
            "test.physical.voltage_angle_mae_deg",
            "test.physical_metrics.voltage_angle_mae_deg",
            "test.metrics.voltage_angle_mae_deg",
            "metrics.test.voltage_angle_mae_deg",
            "physical_metrics.voltage_angle_mae_deg",
            "physical.voltage_angle_mae_deg",
            "test.va_mae_deg",
            "test.v_angle_mae_deg",
            "va_mae_deg",
            "v_angle_mae_deg",
        ],
        "voltage_angle_mae_deg",
        required=require_physical_metrics,
    )

    active_power_mae_mw = _optional_float(
        flattened,
        [
            "active_power_mae_mw",
            "test.active_power_mae_mw",
            "test.physical.active_power_mae_mw",
            "test.physical_metrics.active_power_mae_mw",
            "test.metrics.active_power_mae_mw",
            "metrics.test.active_power_mae_mw",
            "physical_metrics.active_power_mae_mw",
            "physical.active_power_mae_mw",
            "test.p_mae_mw",
            "test.active_p_mae_mw",
            "p_mae_mw",
            "active_p_mae_mw",
        ],
        "active_power_mae_mw",
        required=require_physical_metrics,
    )

    reactive_power_mae_mvar = _optional_float(
        flattened,
        [
            "reactive_power_mae_mvar",
            "test.reactive_power_mae_mvar",
            "test.physical.reactive_power_mae_mvar",
            "test.physical_metrics.reactive_power_mae_mvar",
            "test.metrics.reactive_power_mae_mvar",
            "metrics.test.reactive_power_mae_mvar",
            "physical_metrics.reactive_power_mae_mvar",
            "physical.reactive_power_mae_mvar",
            "test.q_mae_mvar",
            "test.reactive_q_mae_mvar",
            "q_mae_mvar",
            "reactive_q_mae_mvar",
        ],
        "reactive_power_mae_mvar",
        required=require_physical_metrics,
    )

    # ------------------------------------------------------------------
    # AC consistency metrics
    # ------------------------------------------------------------------

    ac_active_power_residual_mae_mw = _optional_float(
        flattened,
        [
            "ac_active_power_residual_mae_mw",
            "test.ac_active_power_residual_mae_mw",
            "test.physical.ac_active_power_residual_mae_mw",
            "test.physical_metrics.ac_active_power_residual_mae_mw",
            "test.metrics.ac_active_power_residual_mae_mw",
            "metrics.test.ac_active_power_residual_mae_mw",
            "physics.ac_active_power_residual_mae_mw",
            "test.physics.ac_active_power_residual_mae_mw",
            "test.ac_residuals.active_power_mae_mw",
            "test.ac_residuals.p_mae_mw",
            "ac_residuals.active_power_mae_mw",
            "ac_residuals.p_mae_mw",
            "ac_p_residual_mae_mw",
            "p_balance_residual_mae_mw",
            "active_power_balance_residual_mae_mw",
        ],
        "ac_active_power_residual_mae_mw",
        required=require_physical_metrics,
    )

    ac_reactive_power_residual_mae_mvar = _optional_float(
        flattened,
        [
            "ac_reactive_power_residual_mae_mvar",
            "test.ac_reactive_power_residual_mae_mvar",
            "test.physical.ac_reactive_power_residual_mae_mvar",
            "test.physical_metrics.ac_reactive_power_residual_mae_mvar",
            "test.metrics.ac_reactive_power_residual_mae_mvar",
            "metrics.test.ac_reactive_power_residual_mae_mvar",
            "physics.ac_reactive_power_residual_mae_mvar",
            "test.physics.ac_reactive_power_residual_mae_mvar",
            "test.ac_residuals.reactive_power_mae_mvar",
            "test.ac_residuals.q_mae_mvar",
            "ac_residuals.reactive_power_mae_mvar",
            "ac_residuals.q_mae_mvar",
            "ac_q_residual_mae_mvar",
            "q_balance_residual_mae_mvar",
            "reactive_power_balance_residual_mae_mvar",
        ],
        "ac_reactive_power_residual_mae_mvar",
        required=require_physical_metrics,
    )

    voltage_violation_rate = _optional_float(
        flattened,
        [
            "voltage_violation_rate",
            "test.voltage_violation_rate",
            "test.physical.voltage_violation_rate",
            "test.physical_metrics.voltage_violation_rate",
            "test.metrics.voltage_violation_rate",
            "metrics.test.voltage_violation_rate",
            "physics.voltage_violation_rate",
            "test.physics.voltage_violation_rate",
            "voltage_limits.violation_rate",
            "test.voltage_limits.violation_rate",
            "voltage_constraint_violation_rate",
        ],
        "voltage_violation_rate",
        required=require_physical_metrics,
    )

    best_validation_epoch = _to_int(
        _candidate_value(
            flattened,
            [
                "best_validation_epoch",
                "best_val_epoch",
                "best_epoch",
                "validation.best_epoch",
                "validation.epoch",
                "metrics.best_validation_epoch",
                "training.best_validation_epoch",
                "training.best_epoch",
                "checkpoint.best_epoch",
            ],
            required=True,
            field_name="best-validation epoch",
        ),
        "best_validation_epoch",
    )

    best_validation_mse = _to_float(
        _candidate_value(
            flattened,
            [
                "best_validation_mse",
                "best_val_mse",
                "validation.best_mse",
                "validation.normalized_mse",
                "metrics.best_validation_mse",
                "training.best_validation_mse",
                "checkpoint.validation_mse",
            ],
            default=float("nan"),
        ),
        "best_validation_mse",
        finite=False,
    )

    training_time_seconds = _to_float(
        _candidate_value(
            flattened,
            [
                "training_time_seconds",
                "train_time_seconds",
                "training_seconds",
                "elapsed_training_seconds",
                "runtime.training_seconds",
                "timing.training_seconds",
                "training.time_seconds",
                "training.elapsed_seconds",
            ],
            required=True,
            field_name="training time",
        ),
        "training_time_seconds",
    )

    parameter_count = _to_int(
        _candidate_value(
            flattened,
            [
                "parameter_count",
                "num_parameters",
                "number_of_parameters",
                "total_parameters",
                "model.parameter_count",
                "model.num_parameters",
                "model.total_parameters",
                "metrics.parameter_count",
            ],
            required=True,
            field_name="parameter count",
        ),
        "parameter_count",
    )

    trainable_parameter_count = _to_int(
        _candidate_value(
            flattened,
            [
                "trainable_parameter_count",
                "trainable_parameters",
                "num_trainable_parameters",
                "model.trainable_parameter_count",
                "model.trainable_parameters",
            ],
            default=parameter_count,
        ),
        "trainable_parameter_count",
    )

    simbench_code = str(
        _candidate_value(
            flattened,
            [
                "simbench_code",
                "grid",
                "grid_code",
                "dataset.simbench_code",
                "config.simbench_code",
                "args.simbench_code",
                "arguments.simbench_code",
                "experiment.simbench_code",
            ],
            default="unknown",
        )
    )

    trajectory_length = _optional_int(
        _candidate_value(
            flattened,
            [
                "trajectory_length",
                "config.trajectory_length",
                "args.trajectory_length",
                "arguments.trajectory_length",
            ],
            default=None,
        ),
        "trajectory_length",
    )

    context_length = _optional_int(
        _candidate_value(
            flattened,
            [
                "context_length",
                "config.context_length",
                "args.context_length",
                "arguments.context_length",
            ],
            default=None,
        ),
        "context_length",
    )

    forecast_length = _optional_int(
        _candidate_value(
            flattened,
            [
                "forecast_length",
                "config.forecast_length",
                "args.forecast_length",
                "arguments.forecast_length",
            ],
            default=None,
        ),
        "forecast_length",
    )

    stride = _optional_int(
        _candidate_value(
            flattened,
            [
                "stride",
                "config.stride",
                "args.stride",
                "arguments.stride",
            ],
            default=None,
        ),
        "stride",
    )

    batch_size = _optional_int(
        _candidate_value(
            flattened,
            [
                "batch_size",
                "config.batch_size",
                "args.batch_size",
                "arguments.batch_size",
                "training.batch_size",
            ],
            default=None,
        ),
        "batch_size",
    )

    prediction_path = str(
        _candidate_value(
            flattened,
            [
                "prediction_path",
                "predictions_path",
                "prediction_file",
                "predictions_file",
                "artifacts.prediction_path",
                "artifacts.predictions_path",
                "outputs.prediction_path",
                "outputs.predictions_path",
                "test.prediction_path",
            ],
            default="",
        )
    )

    alias = str(
        _candidate_value(
            flattened,
            [
                "alias",
                "config.alias",
                "args.alias",
                "arguments.alias",
                "experiment.alias",
            ],
            default="",
        )
    )

    _validate_nonnegative_metric(
        normalized_test_mse,
        "normalized_test_mse",
        path,
    )
    _validate_nonnegative_metric(
        normalized_test_mae,
        "normalized_test_mae",
        path,
    )
    _validate_nonnegative_metric(
        voltage_magnitude_mae_pu,
        "voltage_magnitude_mae_pu",
        path,
    )
    _validate_nonnegative_metric(
        voltage_angle_mae_deg,
        "voltage_angle_mae_deg",
        path,
    )
    _validate_nonnegative_metric(
        active_power_mae_mw,
        "active_power_mae_mw",
        path,
    )
    _validate_nonnegative_metric(
        reactive_power_mae_mvar,
        "reactive_power_mae_mvar",
        path,
    )
    _validate_nonnegative_metric(
        ac_active_power_residual_mae_mw,
        "ac_active_power_residual_mae_mw",
        path,
    )
    _validate_nonnegative_metric(
        ac_reactive_power_residual_mae_mvar,
        "ac_reactive_power_residual_mae_mvar",
        path,
    )
    _validate_rate(
        voltage_violation_rate,
        "voltage_violation_rate",
        path,
    )

    if best_validation_epoch < 0:
        raise ValueError(
            f"best_validation_epoch cannot be negative: {path}"
        )

    if training_time_seconds < 0.0:
        raise ValueError(
            f"training_time_seconds cannot be negative: {path}"
        )

    if parameter_count < 0:
        raise ValueError(
            f"parameter_count cannot be negative: {path}"
        )

    if trainable_parameter_count < 0:
        raise ValueError(
            f"trainable_parameter_count cannot be negative: {path}"
        )

    if trainable_parameter_count > parameter_count:
        raise ValueError(
            "trainable_parameter_count cannot exceed parameter_count in "
            f"{path}: {trainable_parameter_count} > {parameter_count}"
        )

    try:
        source_file = str(path.relative_to(input_directory))
    except ValueError:
        source_file = str(path)

    return ParsedResult(
        source_file=source_file,
        simbench_code=simbench_code,
        task=task,
        observed_fraction=observed_fraction,
        model=model,
        seed=seed,
        mask_seed=mask_seed,
        normalized_test_mse=normalized_test_mse,
        normalized_test_mae=normalized_test_mae,
        normalized_test_mse_full=normalized_test_mse_full,
        normalized_test_mae_full=normalized_test_mae_full,
        normalized_test_mse_unobserved=(
            normalized_test_mse_unobserved
        ),
        normalized_test_mae_unobserved=(
            normalized_test_mae_unobserved
        ),
        voltage_magnitude_mae_pu=voltage_magnitude_mae_pu,
        voltage_angle_mae_deg=voltage_angle_mae_deg,
        active_power_mae_mw=active_power_mae_mw,
        reactive_power_mae_mvar=reactive_power_mae_mvar,
        ac_active_power_residual_mae_mw=(
            ac_active_power_residual_mae_mw
        ),
        ac_reactive_power_residual_mae_mvar=(
            ac_reactive_power_residual_mae_mvar
        ),
        voltage_violation_rate=voltage_violation_rate,
        best_validation_epoch=best_validation_epoch,
        best_validation_mse=best_validation_mse,
        training_time_seconds=training_time_seconds,
        parameter_count=parameter_count,
        trainable_parameter_count=trainable_parameter_count,
        trajectory_length=trajectory_length,
        context_length=context_length,
        forecast_length=forecast_length,
        stride=stride,
        batch_size=batch_size,
        prediction_path=prediction_path,
        alias=alias,
    )


def _find_json_files(
    input_directory: Path,
    pattern: str,
    output_directory: Path,
) -> List[Path]:
    files = []

    for path in input_directory.glob(pattern):
        if not path.is_file() or path.suffix.lower() != ".json":
            continue

        try:
            path.resolve().relative_to(output_directory.resolve())
            inside_output = True
        except ValueError:
            inside_output = False

        if inside_output and output_directory != input_directory:
            continue

        files.append(path)

    return sorted(files)


def load_results(
    input_directory: Path,
    pattern: str,
    output_directory: Path,
    *,
    strict: bool,
    require_physical_metrics: bool = False,
) -> pd.DataFrame:
    files = _find_json_files(
        input_directory,
        pattern,
        output_directory,
    )

    if not files:
        raise FileNotFoundError(
            f"No JSON files matched {pattern!r} under {input_directory}"
        )

    parsed: List[ParsedResult] = []
    skipped: List[Tuple[Path, str]] = []

    for path in files:
        try:
            parsed.append(
                _parse_result_json(
                    path,
                    input_directory,
                    require_physical_metrics=(
                        require_physical_metrics
                    ),
                )
            )
        except (KeyError, TypeError, ValueError) as exc:
            if strict or require_physical_metrics:
                raise RuntimeError(
                    f"Could not parse result file {path}: {exc}"
                ) from exc

            skipped.append((path, str(exc)))

    for path, reason in skipped:
        warnings.warn(
            f"Skipping non-result or malformed JSON {path}: {reason}",
            stacklevel=2,
        )

    if not parsed:
        raise RuntimeError(
            "No valid power-grid result JSON files were found"
        )

    frame = pd.DataFrame(
        [item.as_dict() for item in parsed]
    )

    frame["task"] = pd.Categorical(
        frame["task"],
        categories=TASK_ORDER,
        ordered=True,
    )
    frame["observed_fraction"] = pd.Categorical(
        frame["observed_fraction"],
        categories=OBSERVATION_FRACTION_ORDER,
        ordered=True,
    )
    frame["model"] = pd.Categorical(
        frame["model"],
        categories=MODEL_ORDER,
        ordered=True,
    )

    frame = frame.sort_values(
        [
            "task",
            "observed_fraction",
            "model",
            "seed",
            "mask_seed",
            "source_file",
        ],
        kind="stable",
    ).reset_index(drop=True)

    frame["task"] = frame["task"].astype(str)
    frame["observed_fraction"] = frame[
        "observed_fraction"
    ].astype(float)
    frame["model"] = frame["model"].astype(str)

    return frame


def _check_duplicate_runs(
    results: pd.DataFrame,
    *,
    allow_duplicates: bool,
) -> None:
    """Detect ambiguous repeated runs."""

    identity = [
        "simbench_code",
        "task",
        "observed_fraction",
        "model",
        "seed",
        "mask_seed",
    ]

    duplicate_mask = results.duplicated(
        identity,
        keep=False,
    )

    if not duplicate_mask.any():
        return

    duplicate_rows = results.loc[
        duplicate_mask,
        identity + ["source_file"],
    ].sort_values(identity)

    message = (
        "Multiple result files have the same experiment identity:\n"
        + duplicate_rows.to_string(index=False)
    )

    if allow_duplicates:
        warnings.warn(
            message
            + "\nDuplicates remain in results.csv and are averaged within "
            "each seed before paired comparisons.",
            stacklevel=2,
        )
    else:
        raise ValueError(
            message
            + "\nRemove duplicate runs or use --allow-duplicates."
        )


def _sample_standard_deviation(
    series: pd.Series,
) -> float:
    values = pd.to_numeric(
        series,
        errors="coerce",
    ).dropna()

    if len(values) < 2:
        return float("nan")

    return float(values.std(ddof=1))


def _finite_mean(
    series: pd.Series,
) -> float:
    values = pd.to_numeric(
        series,
        errors="coerce",
    )
    values = values[np.isfinite(values)]

    if values.empty:
        return float("nan")

    return float(values.mean())


def _nonmissing_count(
    series: pd.Series,
) -> int:
    values = pd.to_numeric(
        series,
        errors="coerce",
    )
    return int(np.isfinite(values).sum())


def _unique_parameter_count(
    series: pd.Series,
) -> Any:
    values = pd.to_numeric(
        series,
        errors="coerce",
    ).dropna().astype(np.int64)

    unique = np.sort(values.unique())

    if unique.size == 0:
        return np.nan

    if unique.size == 1:
        return int(unique[0])

    # Multiple counts normally indicate an accidental architecture mismatch.
    return "|".join(
        str(int(value))
        for value in unique
    )


def _metric_summary(
    group: pd.DataFrame,
    source_column: str,
    output_prefix: str,
) -> Dict[str, Any]:
    return {
        f"mean_{output_prefix}": _finite_mean(
            group[source_column]
        ),
        f"std_{output_prefix}": _sample_standard_deviation(
            group[source_column]
        ),
        f"count_{output_prefix}": _nonmissing_count(
            group[source_column]
        ),
    }


def build_summary(
    results: pd.DataFrame,
) -> pd.DataFrame:
    """Build the task/fraction/model paper-metric summary."""

    group_columns = [
        "task",
        "observed_fraction",
        "model",
    ]

    rows: List[Dict[str, Any]] = []

    for keys, group in results.groupby(
        group_columns,
        sort=False,
        observed=True,
    ):
        task, observed_fraction, model = keys

        row: Dict[str, Any] = {
            "task": task,
            "observed_fraction": float(observed_fraction),
            "model": model,
            "model_display_name": _display_model_name(model),
            "number_of_seeds": int(group["seed"].nunique()),
            "number_of_runs": int(len(group)),
        }

        row.update(
            _metric_summary(
                group,
                "normalized_test_mse",
                "normalized_mse",
            )
        )
        row.update(
            _metric_summary(
                group,
                "normalized_test_mae",
                "normalized_mae",
            )
        )
        row.update(
            _metric_summary(
                group,
                "normalized_test_mse_full",
                "normalized_mse_full",
            )
        )
        row.update(
            _metric_summary(
                group,
                "normalized_test_mae_full",
                "normalized_mae_full",
            )
        )
        row.update(
            _metric_summary(
                group,
                "normalized_test_mse_unobserved",
                "normalized_mse_unobserved",
            )
        )
        row.update(
            _metric_summary(
                group,
                "normalized_test_mae_unobserved",
                "normalized_mae_unobserved",
            )
        )
        row.update(
            _metric_summary(
                group,
                "voltage_magnitude_mae_pu",
                "voltage_magnitude_mae_pu",
            )
        )
        row.update(
            _metric_summary(
                group,
                "voltage_angle_mae_deg",
                "voltage_angle_mae_deg",
            )
        )
        row.update(
            _metric_summary(
                group,
                "active_power_mae_mw",
                "active_power_mae_mw",
            )
        )
        row.update(
            _metric_summary(
                group,
                "reactive_power_mae_mvar",
                "reactive_power_mae_mvar",
            )
        )
        row.update(
            _metric_summary(
                group,
                "ac_active_power_residual_mae_mw",
                "ac_active_power_residual_mae_mw",
            )
        )
        row.update(
            _metric_summary(
                group,
                "ac_reactive_power_residual_mae_mvar",
                "ac_reactive_power_residual_mae_mvar",
            )
        )
        row.update(
            _metric_summary(
                group,
                "voltage_violation_rate",
                "voltage_violation_rate",
            )
        )

        row.update(
            {
                "mean_best_validation_epoch": _finite_mean(
                    group["best_validation_epoch"]
                ),
                "std_best_validation_epoch": (
                    _sample_standard_deviation(
                        group["best_validation_epoch"]
                    )
                ),
                "mean_best_validation_mse": _finite_mean(
                    group["best_validation_mse"]
                ),
                "std_best_validation_mse": (
                    _sample_standard_deviation(
                        group["best_validation_mse"]
                    )
                ),
                "mean_training_time_seconds": _finite_mean(
                    group["training_time_seconds"]
                ),
                "std_training_time_seconds": (
                    _sample_standard_deviation(
                        group["training_time_seconds"]
                    )
                ),
                "parameter_count": _unique_parameter_count(
                    group["parameter_count"]
                ),
                "trainable_parameter_count": (
                    _unique_parameter_count(
                        group["trainable_parameter_count"]
                    )
                ),
            }
        )

        # Compatibility aliases for plotting/reporting tools that use the
        # metric-name-first convention.
        row["normalized_test_mse_mean"] = row[
            "mean_normalized_mse"
        ]
        row["normalized_test_mse_std"] = row[
            "std_normalized_mse"
        ]
        row["normalized_test_mae_mean"] = row[
            "mean_normalized_mae"
        ]
        row["normalized_test_mae_std"] = row[
            "std_normalized_mae"
        ]

        rows.append(row)

    summary = pd.DataFrame(rows)

    summary["task"] = pd.Categorical(
        summary["task"],
        categories=TASK_ORDER,
        ordered=True,
    )
    summary["observed_fraction"] = pd.Categorical(
        summary["observed_fraction"],
        categories=OBSERVATION_FRACTION_ORDER,
        ordered=True,
    )
    summary["model"] = pd.Categorical(
        summary["model"],
        categories=MODEL_ORDER,
        ordered=True,
    )

    summary = summary.sort_values(
        [
            "task",
            "observed_fraction",
            "model",
        ],
        kind="stable",
    ).reset_index(drop=True)

    summary["task"] = summary["task"].astype(str)
    summary["observed_fraction"] = summary[
        "observed_fraction"
    ].astype(float)
    summary["model"] = summary["model"].astype(str)

    return summary


def _collapse_runs_for_pairing(
    results: pd.DataFrame,
) -> pd.DataFrame:
    """
    Produce one row per paired identity and model.

    Duplicate runs are averaged within each seed before pairing.
    """

    grouping = [
        "simbench_code",
        "task",
        "observed_fraction",
        "seed",
        "mask_seed",
        "model",
    ]

    metric_columns = [
        "normalized_test_mse",
        "normalized_test_mae",
        "voltage_magnitude_mae_pu",
        "voltage_angle_mae_deg",
        "active_power_mae_mw",
        "reactive_power_mae_mvar",
        "ac_active_power_residual_mae_mw",
        "ac_reactive_power_residual_mae_mvar",
        "voltage_violation_rate",
    ]

    aggregations: Dict[str, Tuple[str, str]] = {
        column: (column, "mean")
        for column in metric_columns
    }
    aggregations["duplicate_run_count"] = (
        "source_file",
        "size",
    )

    return (
        results.groupby(
            grouping,
            as_index=False,
            sort=False,
            observed=True,
        )
        .agg(**aggregations)
    )


def _safe_relative_improvement(
    challenger: pd.Series,
    baseline: pd.Series,
) -> pd.Series:
    """
    Compute 100 * (baseline - challenger) / baseline.

    A zero baseline produces NaN rather than an infinite percentage.
    """

    challenger = challenger.astype(float)
    baseline = baseline.astype(float)

    denominator = baseline.where(
        baseline.abs() > 0.0,
        np.nan,
    )

    return 100.0 * (
        baseline - challenger
    ) / denominator


def _paired_metric_statistics(
    paired: pd.DataFrame,
    column_a: str,
    column_b: str,
    output_name: str,
) -> Dict[str, Any]:
    """
    Compute paired absolute and relative improvements for one metric.

    Positive values mean model A has a lower error/residual than model B.
    """

    valid = paired[
        np.isfinite(paired[column_a])
        & np.isfinite(paired[column_b])
    ]

    if valid.empty:
        return {
            f"number_of_{output_name}_pairs": 0,
            f"mean_{output_name}_model_a": np.nan,
            f"mean_{output_name}_model_b": np.nan,
            f"mean_{output_name}_improvement_model_a": np.nan,
            f"std_{output_name}_improvement_model_a": np.nan,
            f"mean_relative_{output_name}_improvement_percent": np.nan,
            f"std_relative_{output_name}_improvement_percent": np.nan,
        }

    improvement = valid[column_b] - valid[column_a]
    relative = _safe_relative_improvement(
        challenger=valid[column_a],
        baseline=valid[column_b],
    )

    return {
        f"number_of_{output_name}_pairs": int(len(valid)),
        f"mean_{output_name}_model_a": float(
            valid[column_a].mean()
        ),
        f"mean_{output_name}_model_b": float(
            valid[column_b].mean()
        ),
        f"mean_{output_name}_improvement_model_a": float(
            improvement.mean()
        ),
        f"std_{output_name}_improvement_model_a": (
            _sample_standard_deviation(improvement)
        ),
        f"mean_relative_{output_name}_improvement_percent": (
            float(relative.mean())
        ),
        f"std_relative_{output_name}_improvement_percent": (
            _sample_standard_deviation(relative)
        ),
    }


def build_paired_comparisons(
    results: pd.DataFrame,
) -> pd.DataFrame:
    """
    Build seed-paired model comparisons.

    Pairing includes grid, task, observed fraction, seed, and mask seed.
    Normalized MSE remains the primary paired comparison. Physical metrics are
    also reported where both paired runs contain them.
    """

    collapsed = _collapse_runs_for_pairing(results)

    pairing_keys = [
        "simbench_code",
        "task",
        "observed_fraction",
        "seed",
        "mask_seed",
    ]

    compared_metrics = [
        "normalized_test_mse",
        "normalized_test_mae",
        "voltage_magnitude_mae_pu",
        "voltage_angle_mae_deg",
        "active_power_mae_mw",
        "reactive_power_mae_mvar",
        "ac_active_power_residual_mae_mw",
        "ac_reactive_power_residual_mae_mvar",
        "voltage_violation_rate",
    ]

    rows: List[Dict[str, Any]] = []

    for group_key, task_fraction_group in collapsed.groupby(
        ["task", "observed_fraction"],
        sort=False,
        observed=True,
    ):
        task, observed_fraction = group_key

        for model_a, model_b, comparison_name in PAIRED_COMPARISONS:
            rename_a = {
                metric: f"{metric}_a"
                for metric in compared_metrics
            }
            rename_b = {
                metric: f"{metric}_b"
                for metric in compared_metrics
            }

            left = task_fraction_group[
                task_fraction_group["model"] == model_a
            ][
                pairing_keys + compared_metrics
            ].rename(columns=rename_a)

            right = task_fraction_group[
                task_fraction_group["model"] == model_b
            ][
                pairing_keys + compared_metrics
            ].rename(columns=rename_b)

            paired = left.merge(
                right,
                on=pairing_keys,
                how="inner",
                validate="one_to_one",
            )

            row: Dict[str, Any] = {
                "task": task,
                "observed_fraction": float(observed_fraction),
                "comparison": comparison_name,
                "model_a": model_a,
                "model_a_display_name": _display_model_name(model_a),
                "model_b": model_b,
                "model_b_display_name": _display_model_name(model_b),
                "number_of_pairs": int(len(paired)),
            }

            if paired.empty:
                for metric in compared_metrics:
                    row.update(
                        _paired_metric_statistics(
                            paired,
                            f"{metric}_a",
                            f"{metric}_b",
                            metric,
                        )
                    )

                row.update(
                    {
                        "median_relative_mse_improvement_percent": np.nan,
                        "win_rate_mse_model_a": np.nan,
                        "tie_rate_mse": np.nan,
                    }
                )
                rows.append(row)
                continue

            for metric in compared_metrics:
                row.update(
                    _paired_metric_statistics(
                        paired,
                        f"{metric}_a",
                        f"{metric}_b",
                        metric,
                    )
                )

            mse_a = paired["normalized_test_mse_a"]
            mse_b = paired["normalized_test_mse_b"]
            valid_mse = np.isfinite(mse_a) & np.isfinite(mse_b)

            if valid_mse.any():
                mse_improvement = (
                    mse_b[valid_mse] - mse_a[valid_mse]
                )
                relative_mse = _safe_relative_improvement(
                    challenger=mse_a[valid_mse],
                    baseline=mse_b[valid_mse],
                )

                tolerance = 1e-12
                wins = mse_improvement > tolerance
                ties = mse_improvement.abs() <= tolerance

                row.update(
                    {
                        "median_relative_mse_improvement_percent": (
                            float(relative_mse.median())
                        ),
                        "win_rate_mse_model_a": float(wins.mean()),
                        "tie_rate_mse": float(ties.mean()),
                    }
                )
            else:
                row.update(
                    {
                        "median_relative_mse_improvement_percent": np.nan,
                        "win_rate_mse_model_a": np.nan,
                        "tie_rate_mse": np.nan,
                    }
                )

            # Backward-compatible names used by existing plotting scripts.
            row["mean_normalized_mse_model_a"] = row[
                "mean_normalized_test_mse_model_a"
            ]
            row["mean_normalized_mse_model_b"] = row[
                "mean_normalized_test_mse_model_b"
            ]
            row["mean_mse_improvement_model_a"] = row[
                "mean_normalized_test_mse_improvement_model_a"
            ]
            row["std_mse_improvement_model_a"] = row[
                "std_normalized_test_mse_improvement_model_a"
            ]
            row["mean_relative_normalized_test_mse_improvement_percent"] = row[
                "mean_relative_normalized_test_mse_improvement_percent"
            ]
            row["std_relative_mse_improvement_percent"] = row[
                "std_relative_normalized_test_mse_improvement_percent"
            ]

            row["mean_normalized_mae_model_a"] = row[
                "mean_normalized_test_mae_model_a"
            ]
            row["mean_normalized_mae_model_b"] = row[
                "mean_normalized_test_mae_model_b"
            ]
            row["mean_mae_improvement_model_a"] = row[
                "mean_normalized_test_mae_improvement_model_a"
            ]
            row["std_mae_improvement_model_a"] = row[
                "std_normalized_test_mae_improvement_model_a"
            ]
            row["mean_relative_mae_improvement_percent"] = row[
                "mean_relative_normalized_test_mae_improvement_percent"
            ]

            rows.append(row)

    paired_comparisons = pd.DataFrame(rows)

    comparison_order = [
        name
        for _, _, name in PAIRED_COMPARISONS
    ]

    paired_comparisons["task"] = pd.Categorical(
        paired_comparisons["task"],
        categories=TASK_ORDER,
        ordered=True,
    )
    paired_comparisons["observed_fraction"] = pd.Categorical(
        paired_comparisons["observed_fraction"],
        categories=OBSERVATION_FRACTION_ORDER,
        ordered=True,
    )
    paired_comparisons["comparison"] = pd.Categorical(
        paired_comparisons["comparison"],
        categories=comparison_order,
        ordered=True,
    )

    paired_comparisons = paired_comparisons.sort_values(
        [
            "task",
            "observed_fraction",
            "comparison",
        ],
        kind="stable",
    ).reset_index(drop=True)

    paired_comparisons["task"] = paired_comparisons[
        "task"
    ].astype(str)
    paired_comparisons["observed_fraction"] = paired_comparisons[
        "observed_fraction"
    ].astype(float)
    paired_comparisons["comparison"] = paired_comparisons[
        "comparison"
    ].astype(str)

    return paired_comparisons


def _atomic_write_csv(
    frame: pd.DataFrame,
    path: Path,
) -> None:
    """Write a CSV atomically."""

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    file_descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=str(path.parent),
    )
    os.close(file_descriptor)

    temporary_path = Path(temporary_name)

    try:
        frame.to_csv(
            temporary_path,
            index=False,
            float_format="%.10g",
        )
        os.replace(
            temporary_path,
            path,
        )
    except Exception:
        temporary_path.unlink(missing_ok=True)
        raise


def _warn_missing_physical_metrics(
    results: pd.DataFrame,
) -> None:
    missing_messages = []

    for column in PHYSICAL_METRIC_COLUMNS:
        missing_count = int(
            pd.to_numeric(
                results[column],
                errors="coerce",
            ).isna().sum()
        )

        if missing_count:
            missing_messages.append(
                f"{column}: {missing_count}/{len(results)} missing"
            )

    if missing_messages:
        warnings.warn(
            "Some result files do not contain all physical reporting "
            "metrics. Missing entries are written as NaN:\n  "
            + "\n  ".join(missing_messages)
            + "\nUse --require-physical-metrics for final paper tables.",
            stacklevel=2,
        )


def _format_metric(
    value: Any,
    *,
    percentage: bool = False,
) -> str:
    if pd.isna(value):
        return "NA"

    numeric = float(value)

    if percentage:
        return f"{100.0 * numeric:.3f}%"

    return f"{numeric:.6g}"


def _print_report(
    results: pd.DataFrame,
    summary: pd.DataFrame,
    paired: pd.DataFrame,
    output_directory: Path,
) -> None:
    number_of_files = len(results)
    number_of_seeds = results["seed"].nunique()

    print(
        f"Aggregated {number_of_files} result files "
        f"across {number_of_seeds} unique seeds."
    )
    print(f"Wrote: {output_directory / 'results.csv'}")
    print(f"Wrote: {output_directory / 'summary.csv'}")
    print(
        f"Wrote: {output_directory / 'paired_comparisons.csv'}"
    )

    transport = paired[
        paired["comparison"] == "AT-ODE versus LG-ODE"
    ]

    if not transport.empty:
        print("\nAT-ODE transport improvement over LG-ODE:")

        for row in transport.itertuples(index=False):
            value = row.mean_relative_normalized_test_mse_improvement_percent
            pairs = row.number_of_pairs

            if pd.isna(value):
                text = "not available"
            else:
                text = f"{value:.3f}%"

            print(
                f"  {row.task}, "
                f"{100.0 * row.observed_fraction:.0f}% observed: "
                f"{text} ({pairs} paired seeds)"
            )

    print("\nPaper metric summary:")

    printable_columns = [
        "task",
        "observed_fraction",
        "model_display_name",
        "number_of_seeds",
        "mean_normalized_mse",
        "mean_voltage_magnitude_mae_pu",
        "mean_voltage_angle_mae_deg",
        "mean_active_power_mae_mw",
        "mean_reactive_power_mae_mvar",
        "mean_ac_active_power_residual_mae_mw",
        "mean_ac_reactive_power_residual_mae_mvar",
        "mean_voltage_violation_rate",
        "mean_training_time_seconds",
        "parameter_count",
    ]

    print(
        summary[printable_columns].to_string(
            index=False,
            na_rep="NA",
        )
    )


def parse_args(
    argv: Optional[Sequence[str]] = None,
) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Aggregate SimBench LG-ODE result JSON files into results.csv, "
            "summary.csv and paired_comparisons.csv, including physical-unit "
            "and AC-consistency metrics."
        )
    )

    parser.add_argument(
        "--input-dir",
        type=Path,
        required=True,
        help="Directory containing experiment result JSON files.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help=(
            "Directory for output CSV files. Defaults to --input-dir."
        ),
    )
    parser.add_argument(
        "--pattern",
        type=str,
        default="**/*.json",
        help=(
            "Glob pattern relative to --input-dir. "
            "Default: **/*.json"
        ),
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help=(
            "Fail on every malformed or unrelated JSON file instead of "
            "warning and skipping it."
        ),
    )
    parser.add_argument(
        "--require-physical-metrics",
        action="store_true",
        help=(
            "Require voltage, power, AC-residual, and voltage-violation "
            "metrics in every result JSON. Recommended for final paper "
            "tables."
        ),
    )
    parser.add_argument(
        "--allow-duplicates",
        action="store_true",
        help=(
            "Allow repeated grid/task/fraction/model/seed/mask-seed runs. "
            "They remain in results.csv and are averaged within each seed "
            "for paired comparisons."
        ),
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Do not print the terminal summary.",
    )

    return parser.parse_args(argv)


def main(
    argv: Optional[Sequence[str]] = None,
) -> int:
    args = parse_args(argv)

    input_directory = args.input_dir.expanduser().resolve()
    output_directory = (
        args.output_dir.expanduser().resolve()
        if args.output_dir is not None
        else input_directory
    )

    if not input_directory.is_dir():
        raise NotADirectoryError(
            f"Input directory does not exist: {input_directory}"
        )

    results = load_results(
        input_directory=input_directory,
        pattern=args.pattern,
        output_directory=output_directory,
        strict=args.strict,
        require_physical_metrics=args.require_physical_metrics,
    )

    _check_duplicate_runs(
        results,
        allow_duplicates=args.allow_duplicates,
    )

    if not args.require_physical_metrics:
        _warn_missing_physical_metrics(results)

    summary = build_summary(results)
    paired_comparisons = build_paired_comparisons(results)

    _atomic_write_csv(
        results,
        output_directory / "results.csv",
    )
    _atomic_write_csv(
        summary,
        output_directory / "summary.csv",
    )
    _atomic_write_csv(
        paired_comparisons,
        output_directory / "paired_comparisons.csv",
    )

    if not args.quiet:
        _print_report(
            results,
            summary,
            paired_comparisons,
            output_directory,
        )

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print(
            "Interrupted.",
            file=sys.stderr,
        )
        raise SystemExit(130)
    except Exception as error:
        print(
            f"Error: {error}",
            file=sys.stderr,
        )
        raise SystemExit(1)
s